// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE42TM3i2kAeOCjr7kdYizoKg1G4z5ygQ',
    appId: '1:27181824328:web:9ec068a68f14ac90c7db7d',
    messagingSenderId: '27181824328',
    projectId: 'flutter-firebase-ifrs',
    authDomain: 'flutter-firebase-ifrs.firebaseapp.com',
    storageBucket: 'flutter-firebase-ifrs.firebasestorage.app',
    measurementId: 'G-YKKS7GXFPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsO8DRqqOQY0ThPLg4RmzCtyWAgF8bY38',
    appId: '1:27181824328:android:45148f1d2b9ac202c7db7d',
    messagingSenderId: '27181824328',
    projectId: 'flutter-firebase-ifrs',
    storageBucket: 'flutter-firebase-ifrs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6UV_DSy9RzvHTdCvCiqf_nW3CCfxhkY',
    appId: '1:27181824328:ios:190318a21e6e38d6c7db7d',
    messagingSenderId: '27181824328',
    projectId: 'flutter-firebase-ifrs',
    storageBucket: 'flutter-firebase-ifrs.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjeto1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc6UV_DSy9RzvHTdCvCiqf_nW3CCfxhkY',
    appId: '1:27181824328:ios:190318a21e6e38d6c7db7d',
    messagingSenderId: '27181824328',
    projectId: 'flutter-firebase-ifrs',
    storageBucket: 'flutter-firebase-ifrs.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjeto1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE42TM3i2kAeOCjr7kdYizoKg1G4z5ygQ',
    appId: '1:27181824328:web:7607e453ce1b6303c7db7d',
    messagingSenderId: '27181824328',
    projectId: 'flutter-firebase-ifrs',
    authDomain: 'flutter-firebase-ifrs.firebaseapp.com',
    storageBucket: 'flutter-firebase-ifrs.firebasestorage.app',
    measurementId: 'G-DDDRV4KPV3',
  );

}